### PR TITLE
Fix blank block for included symbols

### PR DESCRIPTION
**Pull request by Realetive**
From this ref: https://github.com/Hiswe/gulp-svg-symbols/issues/23#issuecomment-162777369

Similarly for other css preprocessors.

### CODE REVIEW

**Comment by artem-malko** [comment]
It is not good idea, to apply styles to page > svg, because the main svg-file can be everywhere on the page. So, we have to set uniq className to it and apply these styles only for that className

**Comment by Realetive** [comment]
@artem-malko np, but then you need to set a new template for gulp-svg-symbols with this unique className (will be good to have a possibility to change it). I think, that short annotation (about what for it) before this hack will be sufficient.

**Comment by artem-malko** [comment]
@Realetive there is one more problem, these styles will be applied to all svg-elements in body. So, first of all, we have to set uniq className.
I've added comment about it to issue in gulp-svg-symbols https://github.com/Hiswe/gulp-svg-symbols/issues/25

**Comment by Realetive** [comment]
Many thx.

**Pull request closed without merging**
